### ISSUE TITLE
Purchase and Training Room Setup

### ISSUE THREAD

**Issue by tkdkel** [tkdkel/CCC-410ITS-03#16]
Once we ensure everything runs properly on the open room PCs, we can puchase the licensing and set up the program on the training room PCs. More testing will follow.

**Comment by tkdkel** [comment]
**Tasks**

- [ ] Make sure everything works well on the open room PCs
- [ ] Purchase licensing
- [ ] Deploy Metactix on training room PCs and set up
- [ ] Have teams/players test again
