### ISSUE TITLE
Sprint 1 Demo and Reflection

### ISSUE THREAD

**Issue by tkdkel** [tkdkel/CCC-410ITS-03#19]
Demo and reflection for sprint 1.

**Comment by tkdkel** [comment]
**Tasks**

<ins>Wiki</ins>
- [x] Deliverable Statement
- [x] Objectives
- [x] References
- [x] Link to project board
- [x] Sprint documentation

<ins>Project Board</ins>
- [x] Milestone for sprint
- [x] Issues per milestone
- [x] Assign issues

<ins>Demo</ins>
- [ ] Overview of sprint objectives
- [ ] Final progress against objectives
- [ ] Goals or objectives that were unmet
- [ ] Hands-on presentation that shows how objectives were met
- [ ] Adjustments to be made based on sprint
