### ISSUE TITLE
Gathering Feedback

### ISSUE THREAD

**Issue by tkdkel** [tkdkel/CCC-410ITS-03#25]
The purpose of this is to have a bunch of players, staff, and students who would generally use the space to test Metactix and give us feedback on things we should change or add (within the limits of what Metactix can do).

**Comment by tkdkel** [comment]
**Tasks**

- [x] Ask teams how accounts have been working and if there have been issues
- [x] See what else they may want implemented
- [x] Figure out if anything is too restricting or causing gameplay issues
