### ISSUE TITLE
Start Documentation

### ISSUE THREAD

**Issue by tkdkel** [tkdkel/CCC-410ITS-03#28]
While notes and simple documentation will be taken throughout the sprints, we will start to finalize it around the end of sprint 3.

**Comment by tkdkel** [comment]
**Tasks**
- [x] Create drafts of documentation for the facility managers
  - [x] Includes how to access the server, how to add a new user, and what parts of the server they need to understand
- [x] Create an FAQ and Known Issues section of the Wiki

**Comment by tkdkel** [comment]
Sections of the Wiki have been created and documentation is being worked on. It will be polished and finalized during Sprint 4.
