### ISSUE TITLE
Finalize Implementation

### ISSUE THREAD

**Issue by tkdkel** [tkdkel/CCC-410ITS-03#32]
What this means will largely be based on the feedback we get. This involves making sure everything is good to go for when we both graduate.

**Comment by tkdkel** [comment]
**Tasks**

- [x] Ensure documentation is complete and error-free
- [x] Make sure managers understand how to properly use the server
- [x] Double-check GPOs
- [x] Handoff server credentials to the students taking over ownership
