### ISSUE TITLE
Finalize Documentation

### ISSUE THREAD

**Issue by tkdkel** [tkdkel/CCC-410ITS-03#33]
Finalizing the documentation of our project to get ready to present.

**Comment by tkdkel** [comment]
**Tasks**
- [x] Finish user creation guide
- [x] Finish FAQs section
- [x] Finish common issues section
- [x] Make a frequently used terminology list
- [x] Create a video going over basics and need-to-know things about the server
