### ISSUE TITLE
Sprint 4 Demo and Reflection

### ISSUE THREAD

**Issue by tkdkel** [tkdkel/CCC-410ITS-03#36]
Demo and reflection for sprint 4.

**Comment by tkdkel** [comment]
**Tasks**

- [x] Sprint in GitHub: Wiki
  - [x] Deliverable Statement: A statement or two that defines your Sprint
  - [x] Objectives: A bullet list of the key objectives for the Sprint
  - [x] References: Update your references section on the wiki to include all your sources
  - [x] Sprint Documentation pages: You should have detailed documentation and write-ups for the tasks you completed during the project
  - [x] Link to your GitHub Project Board
- [x] Milestone 4: Project Board
  - [x] Includes Milestone(s) for your Sprint with key goals and assign them to your project
  - [x] Includes Issues - (which are actually specific tasks)- for each Milestone
    - [x] Include discrete and detailed tasks to track the work you are doing
  - [x] Assign these to your Milestone and Project and track them through cards in your project board
- [x] Demonstration/Presentation 
  - [x] An overview of the Sprint objectives
  - [x] Your final progress against these objectives
  - [x] Any goals or objectives that were unmet
  - [x] A hands on demonstration/presentation that shows how you met these objectives
  - [x] Lastly, discuss any adjustments you will make to your project  based upon this sprint
