### ISSUE TITLE
Handoff

### ISSUE THREAD

**Issue by tkdkel** [tkdkel/CCC-410ITS-03#47]
Once finished, we need to hand the project off to the other managers. This will include training them on general management, troubleshooting, upkeep/maintenance, and important things to know. It should be relatively easy since they are also cybersecurity majors.

**Comment by tkdkel** [comment]
**Tasks:**
- [x] Train people we are handing project off to
- [x] Ensure they understand everything
- [x] Give domain/enterprise admin to their accounts
