### ISSUE TITLE
New GPO to Prevent Updates

### ISSUE THREAD

**Issue by tkdkel** [tkdkel/CCC-410ITS-03#48]
Recently, I found out that regular users can update the PCs from Windows 10 to Windows 11 because a GPO was never added to prevent updates. This should be an easy fix, but now I am going to have to go back and revert the PCs that got updated.

**Comment by tkdkel** [comment]
**Tasks**
- [x] Create GPO to restrict normal users from updating Windows at all
- [x] Create GPO to restrict facility managers from updating to Windows 11
  - [x] Only enterprise/domain admins should be able to update to Windows 11
